# Generated by Django 5.0.7 on 2026-09-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('title', models.CharField(max_length=200, verbose_name='Título o curso')),
                ('period', models.CharField(max_length=100, verbose_name='Período')),
                ('details', models.TextField(blank=True, verbose_name='Detalle adicional')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Formación',
                'verbose_name_plural': 'Formaciones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('position', models.CharField(max_length=200, verbose_name='Puesto')),
                ('date_range', models.CharField(help_text='Ejemplo: 2023 - 2024', max_length=100, verbose_name='Período')),
                ('description', models.TextField(blank=True, verbose_name='Descripción breve')),
                ('responsibilities', models.TextField(help_text='Escribir una lista breve en texto.', verbose_name='Responsabilidades')),
                ('tools', models.CharField(blank=True, max_length=300, verbose_name='Herramientas relacionadas')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Proyecto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('technologies', models.CharField(blank=True, max_length=300, verbose_name='Tecnologías')),
                ('category', models.CharField(choices=[('web', 'Desarrollo web'), ('qa', 'QA / Testing'), ('education', 'Formación académica'), ('other', 'Otro')], default='web', max_length=50, verbose_name='Categoría')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagen')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='Demo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Franco Irusta', max_length=120, verbose_name='Nombre del sitio')),
                ('page_title', models.CharField(default='Franco Irusta | IT Support & QA Manual', max_length=200, verbose_name='Título de la página')),
                ('meta_description', models.TextField(default='CV profesional de Franco Irusta, enfocado en IT Support y QA Manual.', verbose_name='Meta description')),
                ('email', models.EmailField(default='franco.cantonati.99@gmail.com', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='+56 9 3906 6796', max_length=50, verbose_name='Teléfono')),
                ('location', models.CharField(default='Santiago Centro, Región Metropolitana', max_length=200, verbose_name='Ubicación')),
                ('linkedin_url', models.URLField(default='https://www.linkedin.com/in/fb-irusta/', verbose_name='LinkedIn')),
                ('github_url', models.URLField(default='https://github.com/', verbose_name='GitHub')),
                ('cv_pdf', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV PDF')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('qa', 'QA / Testing'), ('it', 'IT / Soporte'), ('development', 'Desarrollo'), ('management', 'Gestión / Versionado')], default='qa', max_length=50, verbose_name='Categoría')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
