# Generated by Django 5.0.7 on 2026-09-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='page_title',
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='github_url',
            field=models.URLField(default='https://github.com/FrancoIrusta', verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(default='CV - Franco B. Irusta', max_length=120, verbose_name='Nombre del sitio'),
        ),
    ]
